# Generated by Django 4.0.4 on 1980-01-01 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='media/images/chats')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('to', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatto', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_question', models.CharField(blank=True, default='', max_length=225)),
                ('secret_answer', models.CharField(blank=True, default='', max_length=225)),
                ('previous_email', models.CharField(blank=True, default='', max_length=225)),
                ('last_token', models.CharField(blank=True, default='', max_length=225)),
                ('profile_updated', models.BooleanField(blank=True, default=False)),
                ('suspension_count', models.IntegerField(blank=True, default=0)),
                ('briefly_suspended', models.BooleanField(blank=True, default=False)),
                ('time_suspended', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_suspended_timestamp', models.IntegerField(blank=True, default=0)),
                ('locked', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=45)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('email_change_request', models.BooleanField(default=False)),
                ('pending_email', models.EmailField(blank=True, default='', max_length=254)),
                ('login_attempt_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='media/images/chats')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.chat')),
                ('reply_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'replies',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=5)),
                ('about', models.TextField(blank=True, default='', max_length=1000)),
                ('rating', models.IntegerField(default=5)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=225)),
                ('photo', models.ImageField(blank=True, upload_to='media/senders/photo')),
                ('profile_edit_date', models.DateField(auto_now=True)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('occupation', models.CharField(blank=True, default='', max_length=5)),
                ('call_code', models.CharField(blank=True, default='', max_length=5)),
                ('trybe', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=5)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=5)),
                ('deleted', models.BooleanField(default=False)),
                ('tc_accepted', models.BooleanField(default=False)),
                ('interested_in', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=200)),
                ('interests', models.CharField(choices=[('science', 'science'), ('art', 'art'), ('photography', 'photography')], default='', max_length=200)),
                ('liked_mangoes', models.ManyToManyField(blank=True, related_name='i_like', to=settings.AUTH_USER_MODEL)),
                ('likes_me', models.ManyToManyField(blank=True, related_name='likes_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=225)),
                ('subject', models.CharField(blank=True, default='', max_length=225)),
                ('entity_id', models.CharField(blank=True, default='', max_length=225)),
                ('message', models.TextField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'help',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/images/profile_pictures')),
                ('is_profile_picture', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pictures',
                'unique_together': {('user', 'is_profile_picture')},
            },
        ),
    ]
