# Generated by Django 4.0.4 on 2022-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_interest_remove_profile_interests_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, default='', to='app.interest'),
        ),
    ]
