# Generated by Django 4.0.4 on 2022-08-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='liked_mangoes',
            new_name='liked_mangos',
        ),
    ]
