# Generated by Django 4.0.4 on 2022-09-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_liked_mangoes_profile_liked_mangos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='sender',
        ),
    ]
