# Generated by Django 4.0.4 on 2022-09-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_chat_image_alter_picture_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set(),
        ),
    ]
